---
# tasks file for roles/utils

- name: install utils
  ansible.builtin.apt:
    name:
      - binutils
      - build-essential
      - bash
      - curl
      - gcc
      - gdb
      - hexedit
      - htop
      - jq
      - ltrace
      - make
      - nano
      - net-tools
      - nload
      - nmap
      - openssl
      - strace
      - tar
      - unzip
      - wget
      - xxd
      - zip
      - zsh
    state: latest

- name: install aws cli
  block:
    - name: download installer
      when: ansible_facts["architecture"] == "aarch64"
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-aarch64.zip
        dest: /tmp
        remote_src: true
        creates: /usr/local/bin/aws
    - name: download installer
      when: ansible_facts["architecture"] != "aarch64"
      ansible.builtin.unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: true
        creates: /usr/local/bin/aws

    - name: install
      ansible.builtin.shell:
        cmd: ./install --install-dir /usr/local/aws-cli --bin-dir /usr/local/bin
        chdir: /tmp/aws
        creates: /usr/local/bin/aws
    - name: remove installation files
      ansible.builtin.file:
        path: /tmp/aws
        state: absent

    - name: configure aws cli
      ansible.builtin.file:
        path: "~{{ awscli_default_user }}/.aws"
        owner: "{{ awscli_default_user }}"
        group: "{{ awscli_default_user }}"
        state: directory
    - name: configure aws cli
      ansible.builtin.template:
        src: .aws.j2
        dest: "~{{ awscli_default_user }}/.aws/config"
        owner: "{{ awscli_default_user }}"
        group: "{{ awscli_default_user }}"

- name: install terraform
  block:
    - name: download installer
      when: ansible_facts["architecture"] == "aarch64"
      ansible.builtin.unarchive:
        src: https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_arm64.zip
        dest: /tmp
        remote_src: true
        creates: /usr/local/bin/terraform
    - name: download installer
      when: ansible_facts["architecture"] != "aarch64"
      ansible.builtin.unarchive:
        src: https://releases.hashicorp.com/terraform/1.6.5/terraform_1.6.5_linux_amd64.zip
        dest: /tmp
        remote_src: true
        creates: /usr/local/bin/terraform

    - name: install
      ansible.builtin.shell:
        cmd: install ./terraform /usr/local/bin
        chdir: /tmp
        creates: /usr/local/bin/terraform
    - name: remove installation files
      ansible.builtin.file:
        path: /tmp/terraform
        state: absent
