---
# tasks file for roles/git

- name: install git
  ansible.builtin.apt:
    name:
      - git
      - git-lfs
    state: latest

- name: ensure git config folder exists
  ansible.builtin.file:
    path: "~{{ git_default_user }}/.config/git"
    state: directory
    owner: "{{ git_default_user }}"
    group: "{{ git_default_user }}"
    recurse: true

- name: create global gitignore-file
  ansible.builtin.template:
    src: ignore.j2
    dest: "~{{ git_default_user }}/.config/git/ignore"
    owner: "{{ git_default_user }}"
    group: "{{ git_default_user }}"

- name: create global gitconfig-file
  ansible.builtin.template:
    src: config.j2
    dest: "~{{ git_default_user }}/.config/git/config"
    owner: "{{ git_default_user }}"
    group: "{{ git_default_user }}"

- name: authorize github key
  become_user: "{{ git_default_user }}"
  ansible.builtin.command: |
    ssh-import-id gh:{{ git_user_name }}
  when: true
